pr:
  branches:
    include:
      - main

trigger: none

pool:
  name: 'Default'

# lockBehavior: sequential
stages:
  - stage: TerraformValidate
    jobs:
      - job: TerraformValidate
        steps:
          - task: TerraformInstaller@1.0.5
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.6.0'
          - task: CmdLine@2
            displayName: Install tflint
            inputs:
              script: |
                echo "Installing tflint tool..."
                curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          - task: CmdLine@2
            displayName: Install tfsec
            inputs:
              script: |
                echo "Installing tfsec tool..."
                curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          - task: CmdLine@2
            displayName: Install commitlint
            inputs:
              script: |
                echo "Installing commitlint tool..."
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
                nvm install 14.7.0
                npm install -g @commitlint/cli @commitlint/config-conventional
                echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
                commitlint --edit
          - task: CmdLine@2
            displayName: Terraform fmt check
            inputs:
              script: |
                echo "Checking if terraform code has been formatted..."
                terraform fmt -recursive -check terraform
          - task: CmdLine@2
            displayName: Terraform lint check
            inputs:
              script: |
                echo "Running tflint..."
                tflint --chdir terraform --init
                tflint --chdir terraform/ --force
          - task: CmdLine@2
            displayName: Terraform security check
            inputs:
              script: |
                echo "Running tfsec..."
                tfsec terraform/
          # - task: CmdLine@2
          #   displayName: Terraform init
          #   inputs:
          #     script: |
          #       export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/secret.json
          #       terraform -chdir=terraform init
          # - task: CmdLine@2
          #   displayName: Terraform validate
          #   inputs:
          #     script: |
          #       export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/secret.json
          #       terraform -chdir=terraform validate