pr:
  branches:
    include:
      - main

trigger: none

pool:
  name: 'Default'

# lockBehavior: sequential
stages:
  - stage: TerraformValidate
    jobs:
      - job: TerraformValidate
        steps:
          - task: TerraformInstaller@1.0.5
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.6.0'
          - task: CmdLine@2
            displayName: Install tflint
            inputs:
              script: |
                echo "Installing tflint tool... \n"
                curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          - task: CmdLine@2
            displayName: Install tfsec
            inputs:
              script: |
                echo "Installing tfsec tool... \n"
                curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          - task: CmdLine@2
            displayName: Terraform fmt check
            inputs:
              script: |
                echo "Checking if terraform code has been formatted... \n"
                terraform fmt -recursive -check terraform
          - task: CmdLine@2
            displayName: Terraform lint check
            inputs:
              script: |
                echo "Running tflint... \n"
                tflint --chdir terraform --init
                tflint --chdir terraform/ --force
          - task: CmdLine@2
            displayName: Terraform security check
            inputs:
              script: |
                echo "Running tfsec... \n"
                tfsec terraform/
          # - task: CmdLine@2
          #   displayName: Terraform init
          #   inputs:
          #     script: |
          #       export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/secret.json
          #       terraform -chdir=terraform init
          # - task: CmdLine@2
          #   displayName: Terraform validate
          #   inputs:
          #     script: |
          #       export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/secret.json
          #       terraform -chdir=terraform validate